version: '3'
services:
  giga.db.user:
    image: postgres:9.4
    ports:
      - "127.0.0.1:9032:5432"
    volumes:
#      - "./data/db_user:/var/lib/postgresql/data"
       - "./init/db_user/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=db_giga_user
      - POSTGRES_USER=user_giga
      - POSTGRES_PASSWORD=gigaboutique
  giga.db.product:
    image: postgres:9.4
    ports:
      - "127.0.0.1:9033:5432"
    volumes:
#      - "./data/db_product:/var/lib/postgresql/data"
       - "./init/db_product/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=db_giga_product
      - POSTGRES_USER=product_giga
      - POSTGRES_PASSWORD=gigaboutique
  giga.db.seller:
    image: postgres:9.4
    ports:
      - "127.0.0.1:9034:5432"
    volumes:
#      - "./data/db_seller:/var/lib/postgresql/data"
       - "./init/db_seller/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=db_giga_seller
      - POSTGRES_USER=seller_giga
      - POSTGRES_PASSWORD=gigaboutique
      
