version: '3'
services:
  giga.db.user:
    image: postgres:9.4
    ports:
      - "127.0.0.1:9032:5432"
    volumes:
#      - "./data/db_user:/var/lib/postgresql/data"
       - "./init/db_user/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=db_giga_user
      - POSTGRES_USER=user_giga
      - POSTGRES_PASSWORD=gigaboutique
  giga.db.product:
    image: postgres:9.4
    ports:
      - "127.0.0.1:9033:5433"
    volumes:
#      - "./data/db_product:/var/lib/postgresql/data"
       - "./init/db_product/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=db_giga_product
      - POSTGRES_USER=product_giga
      - POSTGRES_PASSWORD=gigaboutique
  giga.db.comment:
    image: postgres:9.4
    ports:
      - "127.0.0.1:9034:5434"
    volumes:
#      - "./data/db_comment:/var/lib/postgresql/data"
       - "./init/db_comment/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=db_giga_comment
      - POSTGRES_USER=comment_giga
      - POSTGRES_PASSWORD=gigaboutique
      
