dist: trusty 
language: java
jdk: 
  - openjdk8
sudo: false
services:
  - docker
before_script:
   - docker-compose -f docker/dev/docker-compose.yml up -d
   - sleep 2m
   - docker-compose -f docker/dev/docker-compose.yml up -d
   - sleep 2m
   - docker-compose -f docker/dev/docker-compose.yml up -d
   - sleep 2m
   - docker-compose -f docker/dev/docker-compose.yml up -d
   - sleep 2m
   - ./configserver.sh
   - ./eureka.sh
script:
   - cd giga-userservice
   - mvn clean package
   - cd ..
   - cd giga-productservice
   - mvn clean package
   - cd ..
   - cd giga-vendeurservice
   - mvn clean package   
#script:
  #- cd config
  #- docker build -t config .
  #- docker run --network="host" -d -p9101:9101 config:latest
  #- sleep 3m
  #- cd ..
  #- cd eureka
  #- docker build -t eureka .
  #- docker run --network="host" -d -p9102:9102 eureka:latest
  #- sleep 3m
  #- cd ..
  #- cd ..
  #- cd ..
  #- cd giga-userservice
  #- mvn clean package
  #- cd ..
  #- cd giga-productservice
  #- mvn clean package
  #- cd ..
  #- cd giga-vendeurservice
  #- mvn clean package
after_script:
  - fuser -k 9102/tcp
  - fuser -k 9101/tcp
  - cd ..
  - docker-compose -f docker/dev/docker-compose.yml down
