spring:
 application:
  name: giga-gateway
 jpa:
  show-sql: true
 h2:
  console:
   enabled: true
 cloud:
  gateway:
   routes:
   - id: userModule
     uri: http://localhost:8001/
     predicates:
     - Path=/utilisateur/**, /panier/**
   - id: productModule
     uri: http://localhost:8002/
     predicates:
     - Path=/produit/**, /categorie/**
   - id: sellerModule
     uri: http://localhost:8003/
     predicates:
     - Path=/vendeur/**
      
server:
 port: 8080
 
#Eureka
eureka:
 client:
  service-url:
   defaultZone: http://localhost:9102/eureka/
                
management:
 security:
  enabled: false
  
#route uri: mettre le nom du microservice tel que defini dans application.properties
       

  
